version: v2
global:
  runner:
    os_image: ubuntu

tasks:
  build-image:
    steps:
    - checkout
    - docker/build:
        image: ghcr.io/razorops-public/rails-sample-app/rails-app
        push: true
        tags: ["latest", "${CI_COMMIT_SHA:0:8}"]
        dockerfile: Dockerfile
        context: .
  ruby-sonar-job:
    runner: sonarsource/sonar-scanner-cli
    steps:
   
    - checkout    
    - commands:
      - |
        sonar-scanner \
         -Dsonar.projectKey=rails-ruby \
         -Dsonar.sources=. \
         -Dsonar.host.url=http://localhost:9000 \
         -Dsonar.login=sqp_f52fea16bafedcc5f0f24bca210e315b210629d9  
