
tasks:
  rails-ruby-sonar-job:
    runner: sonarsource/sonar-scanner-cli
    steps:
   
    - checkout    
    - commands:
      - |
       sonar-scanner \
         -Dsonar.projectKey=rails-ruby \
         -Dsonar.sources=. \
         -Dsonar.host.url=http://localhost:9000 \
         -Dsonar.login=sqp_f52fea16bafedcc5f0f24bca210e315b210629d9  
