
tasks:
  rails-ruby-sonar-job:
    runner: sonarsource/sonar-scanner-cli
    steps:
   
    - checkout    
    - commands:
      - |
       sonar-scanner.bat -D"sonar.projectKey=rails-ruby" -D"sonar.sources=." -D"sonar.host.url=http://localhost:9000"
