version: v2
global:
  runner:
    os_image: ubuntu

tasks:
  build-image:
    steps:
    - checkout
    - docker/build:
        image: ghcr.io/razorops-public/rails-sample-app/rails-app
        push: true
        tags: ["latest", "${CI_COMMIT_SHA:0:8}"]
        dockerfile: Dockerfile
        context: .
  ruby-sonar-job:
    runner: sonarsource/sonar-scanner-cli
    steps:
   
    - checkout    
    - commands:
      - |
        sonar-scanner.bat -D"sonar.projectKey=rails-ruby" -D"sonar.sources=." -D"sonar.host.url=http://localhost:9000"       

