
tasks:
  rails-ruby-sonar-job:
    runner: sonarsource/sonar-scanner-cli
    steps:
   
    - checkout    
    - commands:
      - |
       sonar-scanner \
         -Dsonar.projectKey=rails-ruby \
         -Dsonar.sources=. \
         -Dsonar.host.url=https://b520-49-249-225-158.in.ngrok.io \
         -Dsonar.login=673f2eaac60ccc1201f5ba77c0e929e7946a819b  
         
         <script src="https://gist.github.com/Razorops-code/4ab5b63259aebd1868804dd57fcc0c8e.js"></script>
         
         
